version: '3.8'

services:
  local-registry:
    image: registry:2
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - local-registry:/var/lib/registry

  destination-registry:
    image: registry:2
    restart: unless-stopped
    ports:
      - 5001:5000
    volumes:
      - destination-registry:/var/lib/registry

volumes:
  local-registry:
  destination-registry:
